### ISSUE TITLE
Create package on Packagist.org to simplify Composer integration

### ISSUE THREAD

**Issue by a-vasyliev** [kkamkou/jqFenster#18]
Hello,

Is it possible to register your package on packagist.org? It will really simplify Composer integration and will allow to avoid mistakes with version used in projects.

P.S. It should not cost much of efforts from your side.

Thanks!

**Comment by kkamkou** [comment]
Hi Andrii! Nice to read you! AFAIK composer is mostly used by php community, and uses `vendor` folder by default. The same thing exists for js community and called `bower`. What we can do is register `jq-fenster` as a package for bower. Afterwards, you can create `.bowerrc` file with `{"directory" : "vendor/etc"}` content. As the result, you can use the full power of `composer for web` :)

Is it acceptable?

**Comment by a-vasyliev** [comment]
Well, I believe we won't introduce new package manager specifically for Javascript for just one package. I'm familiar with Bower, but unfortunately we have not so much packages to require through it.
  
Thanks anyway!
